# MegaLinter - code quality and downloadable auto-fixes.
# https://megalinter.io
---
name: MegaLinter

on: # yamllint disable-line rule:truthy
  push:
    branches: [main]
  pull_request: null

concurrency:
  group: megalinter-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  megalinter:
    name: MegaLinter
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      pull-requests: write
      checks: write

    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: MegaLinter
        id: megalinter
        uses: oxsecurity/megalinter/flavors/javascript@v9
        env:
          MEGALINTER_CONFIG: .github/linters/.mega-linter.yml
          VALIDATE_ALL_CODEBASE: >-
            ${{
              github.event_name == 'push' &&
              contains(fromJSON('["refs/heads/main", "refs/heads/master"]'), github.ref)
            }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          APPLY_FIXES_EVENT: none

      - name: Prepare MegaLinter fixes
        if: always() && steps.megalinter.outputs.has_updated_sources == '1'
        run: git diff --binary --no-ext-diff > megalinter-fixes.patch

      - name: Archive MegaLinter fixes
        if: always() && steps.megalinter.outputs.has_updated_sources == '1'
        uses: actions/upload-artifact@v7
        with:
          name: MegaLinter fixes
          include-hidden-files: "true"
          retention-days: 14
          if-no-files-found: error
          path: |
            megalinter-fixes.patch
            megalinter-reports/updated_sources

      - name: Archive MegaLinter reports
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: MegaLinter reports
          include-hidden-files: "true"
          retention-days: 7
          path: |
            megalinter-reports
            !megalinter-reports/updated_sources/**
            mega-linter.log
